export const QURAN_STATS = {
  totalWords: 77430, // Approximate standard count without basmalas
  totalAyahs: 6236,
  totalSuras: 114,
  totalJuzs: 30,
  totalHizbs: 60,
  totalRubus: 240,
  totalLetters: 320015,
  makkiSuras: 86,
  madaniSuras: 28,
  longestSura: "البقرة (286 آية)",
  shortestSura: "الكوثر (3 آيات)",
  longestAyah: "آية الدّين (البقرة 282)",
  shortestAyah: "مدهامّتان (الرحمن 64)",
  sajdahs: 15,
  longestWord: "فأسقيناكموه (11 حرفاً - الحجر 22)",
  middleWord: "وليتلطف (الكهف 19)",
  prophetsMentioned: 25,
  suraWithoutBasmala: "التوبة",
  suraWithTwoBasmalas: "النمل",
  suraNamedAfterWoman: "مريم",
  surasNamedAfterProphets: "يونس، هود، يوسف، إبراهيم، محمد، نوح",
  wordFrequencies: [
    { word: "الله", count: 2699 },
    { word: "الرحمن", count: 57 },
    { word: "الرحيم", count: 114 },
    { word: "الدنيا", count: 115 },
    { word: "الآخرة", count: 115 },
    { word: "الملائكة", count: 88 },
    { word: "الشياطين", count: 88 },
    { word: "الحياة", count: 145 },
    { word: "الموت", count: 145 },
    { word: "الرجل", count: 24 },
    { word: "المرأة", count: 24 },
    { word: "موسى", count: 136 },
    { word: "إبراهيم", count: 69 },
    { word: "عيسى", count: 25 },
    { word: "محمد", count: 4 },
    { word: "آدم", count: 25 },
    { word: "نوح", count: 43 },
    { word: "الجنة", count: 77 },
    { word: "النار", count: 77 },
    { word: "الشمس", count: 33 },
    { word: "النور", count: 33 },
    { word: "النبات", count: 26 },
    { word: "الشجر", count: 26 },
  ]
};
